### ISSUE TITLE
Incomplete Wiki - Tom Abbott

### ISSUE THREAD

**Issue by Joshman55** [DMU-CTEC2902/LC-TeamNiche#13]
Please finish your wiki defining your roles and responsibilities.

**Comment by Nuvelle** [comment]
[Done!](https://github.com/DMU-CTEC2902/LC-TeamNiche/wiki/Tom-Abbott)

**Comment by Nuvelle** [comment]
[Done!](https://github.com/DMU-CTEC2902/LC-TeamNiche/wiki/Tom-Abbott)
