### ISSUE TITLE
Incomplete Wiki - Luke Johnson

### ISSUE THREAD

**Issue by Joshman55** [DMU-CTEC2902/LC-TeamNiche#14]
Please finish your wiki defining your roles and responsibilities.

**Comment by lukejohnson32** [comment]
@Joshman55. I have made some of the wiki but we have not yet decided what classes each of us are going to do, so I have not put this in the wiki yet. Can you have a look and see if this is alright. Thanks

**Comment by lukejohnson32** [comment]
Completed.
